image: node:8

variables:
  NODE_ENV: gitlab-ci

mobile_music:
  script:
    - cd mobile_music
    - yarn --frozen-lockfile
    - yarn lint
    - yarn build
pc_music:
  script:
    - cd pc_music
    - yarn --frozen-lockfile
    - yarn lint
    - yarn build

server_api:
  script:
    - cd server_api
    - yarn --frozen-lockfile
    - yarn test