language: node_js
node_js:
- 8.9.4
after_success:
- ssh root@115.159.27.203 -p yyy 'cd /var/www/node/ck-music && git pull && cd mobile_music && yarn build'
before_install:
- openssl aes-256-cbc -K $encrypted_b8b0f2101fc0_key -iv $encrypted_b8b0f2101fc0_iv
  -in id_rsa_home.enc -out ~/.ssh/id_rsa_home -d
