language: node_js

node_js:
- 8.9.4

addons:
  ssh_known_hosts: 115.159.27.203

before_install:
  - openssl aes-256-cbc -K $encrypted_2daa33aa331c_key -iv $encrypted_2daa33aa331c_iv -in tx_rsa.enc -out ~/.ssh/tx_rsa -d
  - chmod 600 ~/.ssh/tx_rsa
  - cat ~/.ssh/tx_rsa
  - echo -e "Host 115.159.27.203\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install: 
  - cd mobile_music
  - yarn

cache:
  directories:
    - "node_modules"

script:
  - yarn build

after_success:
  - ssh root@115.159.27.203 'cd /var/www/node/ck-music && git fetch && git pull && cd mobile_music && yarn && yarn build'

notifications:
  email: false