language: node_js

node_js:
- 8.9.4

addons:
  ssh_known_hosts: 115.159.27.203

jobs:
  include:
    - stage: before_install
    - script:
      - openssl aes-256-cbc -K $encrypted_2daa33aa331c_key -iv $encrypted_2daa33aa331c_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
      - chmod 600 ~/.ssh/id_rsa
      - echo -e "Host 115.159.27.203\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - stage: install
    - script: 
      - cd mobile_music && yarn && cd ..
      - cd pc_music && yarn && cd ..
      - cd server_api && yarn && cd ..
    - stage: test
    - script: .
      -  cd mobile_music && yarn lint && yarn build && cd ..
      -  cd pc_music && yarn lint && yarn build && cd ..
      -  cd server_api && yarn test && cd ..
    - stage: deploy
    - script:
      - ssh root@115.159.27.203 'cd /var/www/node/ck-music && git fetch && git pull && cd mobile_music && yarn && yarn build && cd .. && cd pc_music && yarn && yarn build && cd .. && cd server_api && yarn && pm2 restart app.js cd ..'

notifications:
  email: false